### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by icearith** [jhermsmeier/github-math-iatemplate#1]
I found that if I leave a blank space after the dollar sign. like:

```latex
$$ D(\mathbf{x})=A(\mathbf{x}) + \mathbf{d} $$
```
It does not rend the math equations correctly.

**Comment by jhermsmeier** [comment]
That's the way the Markdown parser ([fletcher/MultiMarkdown-5](https://github.com/fletcher/MultiMarkdown-5)) used by iA Writer works – please file an issue there, if you feel that needs changing.

For more details on how templates work, check https://github.com/iainc/iA-Writer-Templates
