### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by justnealpatel** [jhermsmeier/github-math-iatemplate#2]
This template is amazing and thanks for your work! One thing that would make it complete is within the code block, being able to have auto-completing parentheses and brackets as well as auto-indenting such as when you write a function declaration and press Enter. Would any of these be possible? Thanks again.

**Comment by jhermsmeier** [comment]
Thanks for the kind words! Yeah, I would like to have that too, but these templates can only control the preview, not the behavior of iA Writer itself, so I'm afraid that's not possible for me to do here. You could write to iA with your suggestions though!
