### ISSUE TITLE
Does not install on ios version

### ISSUE THREAD

**Issue by nstarman** [jhermsmeier/github-math-iatemplate#3]

**Comment by nstarman** [comment]
[video showing unknown error](https://share.icloud.com/photos/0MQli3Kptwly6CqJkHU5s23UA)

**Comment by jhermsmeier** [comment]
Thanks @nstarman, I see the issue now. Unfortunately the iA documentation doesn't go into detail about this mechanism, but my current guess is that you'll have to download & unzip the archive first, before you can open the contained .iatemplate bundle with iA Writer.

**Comment by mitastah** [comment]
@jhermsmeier, totally correct. I could install version Version 1.3.1 on my iphone by unzipping and sending the 'github-mathml.iatemplate' folder via airdrop. After that, open it with iA Writer and it shows in the template section. 

Once this is done, using the preview it can be enabled via "Aa" button on the lower left. Works perfectly fine, good job!

**Comment by willzhqiang** [comment]
Thanks, @mitastah , I also did it successfully in iPhone.
