### ISSUE TITLE
Dark version

### ISSUE THREAD

**Issue by calope** [jhermsmeier/github-math-iatemplate#4]
Congratulations about the plugins It's fantastical.

It'would be great the template work in dark mode.

**Comment by jhermsmeier** [comment]
Thanks! I'll see if I can add that when I update it the next time

**Comment by zzfmyway** [comment]
> Thanks! I'll see if I can add that when I update it the next time

Thanks for the template! 

I tried to add night-mode to use another .css from highlight.js, but didn't make it work. Look forward to your new template with night mode support.

**Comment by Dorson** [comment]
> template with night mode support.

Coded the dark mode switch in JS and basic CSS. In my version the multiple color themes can be defined inside of one CSS style file. Many color theme in one file :-)

Try it on the Github demo page :
https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

Feel free to fork, copy, adopt, etc...

Have fun ! :+1:
